# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Room',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('roomno', models.IntegerField()),
                ('floor', models.CharField(max_length=32)),
                ('status', models.TextField()),
            ],
        ),
    ]
