# -*- coding: utf-8 -*-
# Generated by Django 1.10.3 on 2016-11-24 20:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='House',
            fields=[
                ('roomno', models.IntegerField(primary_key=True, serialize=False)),
                ('floor', models.CharField(max_length=32)),
                ('status', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='HouseCategory',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=155)),
            ],
        ),
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('secondname', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=255)),
                ('roomnumber', models.IntegerField()),
                ('nooftenant', models.CharField(max_length=10)),
            ],
        ),
    ]
