# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-21 20:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homedashboard', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('firstname', models.CharField(max_length=255)),
                ('secondname', models.CharField(max_length=255)),
                ('occupation', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=254)),
                ('description', models.CharField(max_length=255)),
                ('roomnumber', models.IntegerField()),
                ('nooftenant', models.IntegerField()),
            ],
        ),
    ]
