# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 08:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homedashboard', '0002_tenant'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tenant',
            name='nooftenant',
            field=models.CharField(max_length=10),
        ),
    ]
