# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-11-22 08:46
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Homedashboard', '0003_auto_20161122_0806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='room',
            name='id',
        ),
        migrations.AlterField(
            model_name='room',
            name='roomno',
            field=models.IntegerField(primary_key=True, serialize=False),
        ),
    ]
